DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE PUBLISHER CASCADE CONSTRAINTS;
DROP TABLE BOOK CASCADE CONSTRAINTS; 
DROP TABLE STAFF CASCADE CONSTRAINTS; 
DROP TABLE BORROW CASCADE CONSTRAINTS; 



CREATE TABLE MEMBER (
    MemberID NUMBER(6), 
    fname VARCHAR2(15), 
    lname VARCHAR2(15),
    Phone NUMBER(11), 
    Address VARCHAR2(20), 
    Email  VARCHAR2(15), 
    CONSTRAINT MEMBER_MEMBER_ID_PK PRIMARY KEY (MemberID)
);

CREATE TABLE PUBLISHER (
    PublisherID NUMBER(6), 
    PublisherName VARCHAR2(15),
    PubAddress VARCHAR2(15), 
    PubEmail VARCHAR2 (10), 
    CONSTRAINT PUBLISHER_PUBLISHER_ID_PK PRIMARY KEY (PublisherID)   
);

CREATE TABLE BOOK (
    BookID NUMBER(5), 
    Title VARCHAR2(10), 
    ISBN NUMBER(13), 
    Year DATE, 
    Genre VARCHAR2(10), 
    PublisherID NUMBER (6), 
    CONSTRAINT BOOK_BOOK_ID_PK PRIMARY KEY (BookID),
    CONSTRAINT BOOK_PUBLISHER_ID_FK FOREIGN KEY (PublisherID) REFERENCES PUBLISHER
);

CREATE TABLE STAFF (
    StaffID NUMBER(6), 
    StaffName VARCHAR2(15),
    Position VARCHAR2(10), 
    StaffEmail VARCHAR2 (10), 
    StaffPhone NUMBER (11), 
    CONSTRAINT STAFF_STAFF_ID_FK PRIMARY KEY (StaffID)
);

CREATE TABLE BORROW (
    BorrowID NUMBER(4), 
    BorrowDate DATE,
    ReturnDate DATE, 
    StaffID NUMBER(6), 
    MemberID NUMBER(6), 
    BookID NUMBER(5),
    CONSTRAINT BORROW_BORROW_ID_PK PRIMARY KEY (BorrowID), 
    CONSTRAINT BORROW_STAFF_ID_FK FOREIGN KEY (StaffID) REFERENCES STAFF,
    CONSTRAINT BORROW_MEMBER_ID_FK FOREIGN KEY (MemberID) REFERENCES MEMBER,
    CONSTRAINT BORROW_BOOK_ID_FK FOREIGN KEY (BookID) REFERENCES BOOK
);
