INSERT INTO PUBLISHER VALUES (100000, 'Kiyosaki', 'Kuantan', 'robertkiyo@gmail.com' ); 
INSERT INTO PUBLISHER VALUES (100001, 'Tolkien', 'Selangor', 'tolkien@gmail.com' ); 
INSERT INTO PUBLISHER VALUES (100002, 'J.K. Rowling', 'Sabah', 'Rowling@gmail.com' ); 
INSERT INTO PUBLISHER VALUES (100003, 'Adnin', 'Kota Bahru', 'dakwahsentap@gmail.com' ); 
INSERT INTO PUBLISHER VALUES (100004, 'Abdul Latip', 'London', 'abdullatiptalib@gmail.com' ); 
INSERT INTO PUBLISHER VALUES (100005, 'Aenid Abdullah', 'Vancouver', 'aenidabdullah@gmail.com' ); 
INSERT INTO PUBLISHER VALUES (100006, 'Prof. Hamka', 'Tokyo', 'Hamkalegend@gmail.com' ); 
INSERT INTO PUBLISHER VALUES (100007, 'Ayman Wong', 'Seoul', 'aymanwong@gmail.com' ); 
INSERT INTO PUBLISHER VALUES (100008, 'Veronica', 'Guangzhou', 'vroth@gmail.com' ); 
INSERT INTO PUBLISHER VALUES (100009, 'Jamil', 'St. Petersburg', 'Jamil@gmail.com' ); 
INSERT INTO PUBLISHER VALUES (100010, 'S. Hawking', 'Melaka', 'eipstein@gmail.com' ); 
